export const EgyptianGovernorates = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Dakahlia",
    "Red Sea",
    "Beheira",
    "Fayoum",
    "Gharbia",
    "Ismailia",
    "Menofia",
    "Minya",
    "Qaliubiya",
    "New Valley",
    "Suez",
    "Aswan",
    "Assiut",
    "Beni Suef",
    "Port Said",
    "Damietta",
    "Sharqia",
    "South Sinai",
    "Kafr El Sheikh",
    "Matruh",
    "Luxor",
    "Qena",
    "North Sinai",
    "Sohag",
  ] as const;
  
  export type Governorate = (typeof EgyptianGovernorates)[number];
  
  export const governorateKeyMap: Record<Governorate, string> = {
    "Cairo": "cairo",
    "Giza": "giza",
    "Alexandria": "alexandria",
    "Dakahlia": "dakahlia",
    "Red Sea": "redSea",
    "Beheira": "beheira",
    "Fayoum": "fayoum",
    "Gharbia": "gharbia",
    "Ismailia": "ismailia",
    "Menofia": "menofia",
    "Minya": "minya",
    "Qaliubiya": "qaliubiya",
    "New Valley": "newValley",
    "Suez": "suez",
    "Aswan": "aswan",
    "Assiut": "assiut",
    "Beni Suef": "beniSuef",
    "Port Said": "portSaid",
    "Damietta": "damietta",
    "Sharqia": "sharqia",
    "South Sinai": "southSinai",
    "Kafr El Sheikh": "kafrElSheikh",
    "Matruh": "matruh",
    "Luxor": "luxor",
    "Qena": "qena",
    "North Sinai": "northSinai",
    "Sohag": "sohag",
  };