import type { Appointment } from "../../components/patient-appointments/AppointmentTypes";
export const mockAppointments: Appointment[] = [
    {
        id: "1",
        doctor: {
            name: "Dr. Sarah Johnson",
            specialty: "Cardiologist",
            photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8901",
            rating: 4.9,
        },
        date: "2026-06-20",
        time: "10:00 AM",
        type: "clinic",
        status: "upcoming",
        reason: "Annual heart checkup",
        reminders: ["Bring ID and insurance card", "Arrive 15 minutes early", "Avoid caffeine 2 hours before"],
        fee: 150,
    },
    {
        id: "2",
        doctor: {
            name: "Dr. Michael Chen",
            specialty: "General Practitioner",
            photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8902",
            rating: 4.7,
        },
        date: "2026-06-25",
        time: "02:30 PM",
        type: "home",
        status: "pending",
        address: "123 Main Street, Apt 4B, New York, NY 10001",
        reason: "Blood pressure monitoring and medication review",
        reminders: ["Ensure clear access to the building", "Have medication list ready"],
        fee: 200,
    },
    {
        id: "3",
        doctor: {
            name: "Dr. Emily Rodriguez",
            specialty: "Dermatologist",
            photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8903",
            rating: 4.8,
        },
        date: "2026-06-05",
        time: "11:00 AM",
        type: "clinic",
        status: "completed",
        reason: "Skin rash consultation",
        reminders: [],
        fee: 120,
    },
    {
        id: "4",
        doctor: {
            name: "Dr. James Wilson",
            specialty: "Orthopedic Surgeon",
            photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8904",
            rating: 4.6,
        },
        date: "2026-05-28",
        time: "09:00 AM",
        type: "clinic",
        status: "cancelled",
        reason: "Knee pain evaluation",
        reminders: [],
        fee: 180,
    },
    {
        id: "5",
        doctor: {
            name: "Dr. Lisa Park",
            specialty: "Neurologist",
            photo: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8905",
            rating: 4.9,
        },
        date: "2026-06-18",
        time: "03:00 PM",
        type: "clinic",
        status: "upcoming",
        reason: "Migraine management consultation",
        reminders: ["Bring list of current medications", "Track headache frequency this week"],
        fee: 160,
    },
    {
        id: "6",
        doctor: {
            name: "Dr. Robert Kim",
            specialty: "Pediatrician",
            photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&h=200&fit=crop",
            phone: "+1 (234) 567-8906",
            rating: 4.8,
        },
        date: "2026-05-15",
        time: "10:30 AM",
        type: "home",
        status: "completed",
        address: "456 Oak Avenue, Brooklyn, NY 11201",
        reason: "Child wellness check and vaccinations",
        reminders: [],
        fee: 220,
        review: {
            rating: 5,
            comment: "Excellent care and attention to detail."
        },
    },
];