name: Backend CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - "backend/**"
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  backend-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: backend-ci-${{ github.ref }}
      cancel-in-progress: true


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: ESLint
        working-directory: ./backend
        run: npm run lint
